name: "Ngrok"
version: "1.0.0"
slug: "ngrok"
description: "Tunel Home Assistant a internet con Ngrok"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
options:
  authtoken: ""
schema:
  authtoken: str
ports:
  8123/tcp: 8123
