name: "Ngrok"
version: "1.1.1"
slug: "ngrok"
description: "Tunel Home Assistant a internet con Ngrok"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
options:
  authtoken: ""  # Token de autenticación de Ngrok
  ngrok_url: ""  # Dirección proporcionada por Ngrok
schema:
  authtoken: str
  ngrok_url: str
ports:
  5050/tcp: 8123
map:
  - config:rw
