name: "Ngrok"
version: "2.2.8"
slug: "ngrok"
description: "Tunel Home Assistant a internet con Ngrok"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
init: false
options:
  authtoken: ""  # Token de autenticación de Ngrok
  ngrok_url: ""  # Dirección proporcionada por Ngrok
schema:
  authtoken: str?
  ngrok_url: str?
#http:
  #server_port: 8123
map:
  - config:rw
